server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.50.10:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.50.217
    username: leyou
    password: leyou
    virtual-host: /leyou
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
