server:
  port: 10010
spring:
  application:
    name: leyou-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #配置禁止使用的头信息，这里设置为null，否则set-cookie无效
  host:
    connect-timeout-millis: 15000 #http连接超时要比hystrix大
    socket-timeout-millis: 60000  #socket超时
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
leyou:
  jwt:
    pubKeyPath:  E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:     # filter拦截的白名单
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
