server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.50.999
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
leyou:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: ly商城验证码 # 签名名称
    verifyCodeTemplate: SMS_191151418 # 模板名称

